version: '3'
services:
  server:
    container_name: alovoa-server
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    image: alovoa
    ports:
      - "8081:8080"
    stdin_open: true
    tty: true
    links:
      - mariadb
  mariadb:
    restart: always
    image: mariadb:10.7
    expose:
      - 3306
    environment:
      MARIADB_DATABASE: alovoaDB
      MARIADB_USER: root
      MARIADB_PASSWORD: example
      MARIADB_ROOT_PASSWORD: example
    volumes:
      - db_data:/var/lib/mariadb
volumes:
  db_data:
