version: '3'
services:
  server:
    container_name: alovoa-server
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    image: alovoa
    extra_hosts:
      - "mysql:172.17.0.1"
    ports:
      - "8080:8080"
    stdin_open: true
    tty: true
    volumes:
      - ./logs:/home/app/logs:cached

