name: Java CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: 'adopt'
        java-version: '17'
        cache: maven
    - uses: shogo82148/actions-setup-mysql@v1
      with:
        distribution: 'mariadb'
        mysql-version: '10.6'
        user: alovoa_test
        password: alovoa_test
    - name: Build with Maven
      run: mvn --batch-mode --update-snapshots verify
